#!/usr/bin/env node
/**
 * Consistency checks between the built CSS and everything that references it.
 * Runs against dist/, so `npm run build` has to happen first.
 *
 *   1. every var(--mw-*) has a definition
 *   2. every --mw-* definition is used somewhere
 *   3. every mw-* class in the markup exists in the built CSS
 *   4. the committed root release files exist and are not empty
 *
 * Sources are scanned rather than hard-coded so a new partial is covered
 * automatically. Exits 1 on any error; warnings never fail the build.
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const CSS = path.join(ROOT, 'dist', 'maverick-wave.min.css');
const HTML = path.join(ROOT, 'dist', 'index.html');
const JS = path.join(ROOT, 'src', 'js', 'main.js');

// Everything that documents classes: the slash command plus every markdown file
// of the maverick-wave skill. Collected by walking the tree, so a new reference
// or example file is covered without touching this list.
const DOCS = [
  path.join(ROOT, '.claude', 'commands', 'mw.md'),
  ...markdownFiles(path.join(ROOT, '.claude', 'skills')),
];

// Tokens read by JavaScript or reserved for consumers, so "unused in CSS" is fine.
// warning/info have no solid button variant, but every status offers the same
// four tones so an application can build one.
const TOKEN_ALLOWLIST = new Set([
  '--mw-internal-theme-mode',
  '--mw-warning-color-hover',
  '--mw-info-color-hover',
]);

// Classes that exist only as JS hooks or are applied by the host application
const CLASS_ALLOWLIST = new Set([]);

const read = (p) => (fs.existsSync(p) ? fs.readFileSync(p, 'utf8') : null);
const all = (str, re) => [...str.matchAll(re)].map((m) => m[1]);

function markdownFiles(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) return markdownFiles(full);
    return entry.name.endsWith('.md') ? [full] : [];
  });
}

const errors = [];
const warnings = [];

const css = read(CSS);
const html = read(HTML);
if (!css || !html) {
  console.error(
    'dist/ is missing or incomplete - run `npm run build` before `npm run verify`.'
  );
  process.exit(1);
}
const js = read(JS) || '';
const docs = DOCS.map(read).filter(Boolean).join('\n');

// --- 1 + 2: custom properties ---------------------------------------------

const tokensDefined = new Set(all(css, /(--mw-[a-z0-9-]+)\s*:/g));
const tokensUsed = new Set([
  ...all(css, /var\((--mw-[a-z0-9-]+)/g),
  ...all(html, /var\((--mw-[a-z0-9-]+)/g),
  ...all(js, /(--mw-[a-z0-9-]+)/g),
]);

for (const t of [...tokensUsed].sort()) {
  if (!tokensDefined.has(t)) {
    errors.push(`token referenced but never defined: var(${t})`);
  }
}
for (const t of [...tokensDefined].sort()) {
  if (!tokensUsed.has(t) && !TOKEN_ALLOWLIST.has(t)) {
    errors.push(
      `token defined but never used: ${t} - overriding it would do nothing`
    );
  }
}

// --- 3: classes ------------------------------------------------------------

const classesInCss = new Set(all(css, /\.(mw-[a-z0-9-]+)/g));

// Classes the JS adds at runtime, or queries as a hook, count as legitimate
// targets - including selector strings like '.mw-foo' and '[class~="mw-foo"]'
const classesInJs = new Set(all(js, /\.?(mw-[a-z0-9-]+)/g));

const classesInMarkup = new Map(); // class -> where it was seen
for (const attr of html.matchAll(/class\s*=\s*"([^"]*)"/g)) {
  for (const c of attr[1].split(/\s+/)) {
    if (c.startsWith('mw-') && !classesInMarkup.has(c)) {
      classesInMarkup.set(c, 'showcase');
    }
  }
}
// The docs name classes as `mw-foo` in prose and code fences. A trailing hyphen
// means a family was written as a stem (`mw-btn-mini-` + variants), never a real
// class - skip those instead of reporting them as missing.
for (const c of all(docs, /[`."'\s](mw-[a-z0-9-]+)/g)) {
  if (c.endsWith('-')) continue;
  if (!classesInMarkup.has(c)) classesInMarkup.set(c, 'docs');
}

for (const [c, where] of [...classesInMarkup].sort()) {
  if (classesInCss.has(c) || classesInJs.has(c) || CLASS_ALLOWLIST.has(c)) {
    continue;
  }
  errors.push(`class used in ${where} but not generated by the CSS: .${c}`);
}

// --- 4: root release files -------------------------------------------------
// These are committed and consumed via jsDelivr and the GitHub release page.
// 4.22.0 shipped without them after `gulp clean` deleted them and the deletion
// got committed - this check makes CI fail instead.

for (const f of ['maverick-wave.min.css', 'maverick-wave.min.js']) {
  const p = path.join(ROOT, f);
  if (!fs.existsSync(p) || fs.statSync(p).size === 0) {
    errors.push(
      `release file missing or empty: ${f} - run \`npm run prepack\` and commit it`
    );
  }
}

// Informational: framework classes the showcase never demonstrates
const undocumented = [...classesInCss].filter(
  (c) => !classesInMarkup.has(c) && !classesInJs.has(c)
);
if (undocumented.length) {
  warnings.push(
    `${undocumented.length} classes exist in the CSS but are not shown in the showcase`
  );
}

// --- report ----------------------------------------------------------------

const label = (n, s) => `${n} ${s}${n === 1 ? '' : 's'}`;

for (const w of warnings) console.log(`  warn   ${w}`);
for (const e of errors) console.error(`  ERROR  ${e}`);

console.log(
  `\nverify: ${tokensDefined.size} tokens, ${classesInCss.size} classes checked - ` +
    (errors.length ? `${label(errors.length, 'error')}` : 'clean')
);

process.exit(errors.length ? 1 : 0);
