#!/usr/bin/env node
/**
 * Consistency checks between the built CSS and everything that references it.
 * Runs against dist/, so `npm run build` has to happen first.
 *
 *   1. every var(--mw-*) has a definition
 *   2. every --mw-* definition is used somewhere
 *   3. every mw-* class in the markup exists in the built CSS
 *   4. the committed root release files match a fresh build
 *   5. the CDN version pinned in the docs matches package.json
 *   6. no `animation:` shorthand in a file that uses a scroll timeline
 *
 * Sources are scanned rather than hard-coded so a new partial is covered
 * automatically. Exits 1 on any error; warnings never fail the build.
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const CSS = path.join(ROOT, 'dist', 'maverick-wave.min.css');
const HTML = path.join(ROOT, 'dist', 'index.html');
const JS = path.join(ROOT, 'src', 'js', 'main.js');

// Everything that documents classes: every markdown file of the maverick-wave
// skill. Collected by walking the tree, so a new reference or example file is
// covered without touching this list.
const DOCS = filesWithExt(path.join(ROOT, '.claude', 'skills'), '.md');

// Tokens read by JavaScript or reserved for consumers, so "unused in CSS" is fine.
// warning/info have no solid button variant, but every status offers the same
// four tones so an application can build one.
const TOKEN_ALLOWLIST = new Set([
  '--mw-internal-theme-mode',
  '--mw-warning-color-hover',
  '--mw-info-color-hover',
]);

// Classes that exist only as JS hooks or are applied by the host application
const CLASS_ALLOWLIST = new Set([]);

const read = (p) => (fs.existsSync(p) ? fs.readFileSync(p, 'utf8') : null);
const all = (str, re) => [...str.matchAll(re)].map((m) => m[1]);

function filesWithExt(dir, ext) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) return filesWithExt(full, ext);
    return entry.name.endsWith(ext) ? [full] : [];
  });
}

const errors = [];
const warnings = [];

const css = read(CSS);
const html = read(HTML);
if (!css || !html) {
  console.error(
    'dist/ is missing or incomplete - run `npm run build` before `npm run verify`.'
  );
  process.exit(1);
}
const js = read(JS) || '';
// The YAML frontmatter of a skill is metadata, not documentation - its
// `name: mw-maverick-wave` would otherwise be reported as a missing class.
const stripFrontmatter = (md) => md.replace(/^---\n[\s\S]*?\n---\n/, '');
const docs = DOCS.map(read).filter(Boolean).map(stripFrontmatter).join('\n');

// --- 1 + 2: custom properties ---------------------------------------------

const tokensDefined = new Set(all(css, /(--mw-[a-z0-9-]+)\s*:/g));
// `\s*` after the paren: a long declaration wrapped by Prettier keeps its
// newline inside var() all the way through the minifier, and a token used only
// there would otherwise read as unused.
const tokensUsed = new Set([
  ...all(css, /var\(\s*(--mw-[a-z0-9-]+)/g),
  ...all(html, /var\(\s*(--mw-[a-z0-9-]+)/g),
  ...all(js, /(--mw-[a-z0-9-]+)/g),
]);

for (const t of [...tokensUsed].sort()) {
  if (!tokensDefined.has(t)) {
    errors.push(`token referenced but never defined: var(${t})`);
  }
}
for (const t of [...tokensDefined].sort()) {
  if (!tokensUsed.has(t) && !TOKEN_ALLOWLIST.has(t)) {
    errors.push(
      `token defined but never used: ${t} - overriding it would do nothing`
    );
  }
}

// --- 3: classes ------------------------------------------------------------

const classesInCss = new Set(all(css, /\.(mw-[a-z0-9-]+)/g));

// Classes the JS adds at runtime, or queries as a hook, count as legitimate
// targets - including selector strings like '.mw-foo' and '[class~="mw-foo"]'
const classesInJs = new Set(all(js, /\.?(mw-[a-z0-9-]+)/g));

const classesInMarkup = new Map(); // class -> where it was seen
for (const attr of html.matchAll(/class\s*=\s*"([^"]*)"/g)) {
  for (const c of attr[1].split(/\s+/)) {
    if (c.startsWith('mw-') && !classesInMarkup.has(c)) {
      classesInMarkup.set(c, 'showcase');
    }
  }
}
// The docs name classes as `mw-foo` in prose and code fences. A trailing hyphen
// means a family was written as a stem (`mw-btn-mini-` + variants), never a real
// class - skip those instead of reporting them as missing.
for (const c of all(docs, /[`."'\s](mw-[a-z0-9-]+)/g)) {
  if (c.endsWith('-')) continue;
  if (!classesInMarkup.has(c)) classesInMarkup.set(c, 'docs');
}

for (const [c, where] of [...classesInMarkup].sort()) {
  if (classesInCss.has(c) || classesInJs.has(c) || CLASS_ALLOWLIST.has(c)) {
    continue;
  }
  errors.push(`class used in ${where} but not generated by the CSS: .${c}`);
}

// --- 4: root release files -------------------------------------------------
// These are committed and consumed via jsDelivr and the GitHub release page.
// 4.22.0 shipped without them after `gulp clean` deleted them and the deletion
// got committed - this check makes CI fail instead.

for (const f of ['maverick-wave.min.css', 'maverick-wave.min.js']) {
  const p = path.join(ROOT, f);
  if (!fs.existsSync(p) || fs.statSync(p).size === 0) {
    errors.push(
      `release file missing or empty: ${f} - run \`npm run prepack\` and commit it`
    );
    continue;
  }
  // `gulp release` runs the same sass/postcss/terser pipeline as the dist tasks
  // and only writes elsewhere, so dist/ is what the committed file has to equal.
  // Existing-and-not-empty was not enough: 5.7.0 shipped a root bundle four
  // commits behind src/, and every CDN consumer got that one.
  if (read(p) !== read(path.join(ROOT, 'dist', f))) {
    errors.push(
      `release file stale: ${f} differs from the fresh build in dist/ - run \`npm run prepack\` and commit it`
    );
  }
}

// --- 5: pinned CDN version -------------------------------------------------
// Every jsDelivr snippet in the docs pins a version, which is the right advice
// and the reason it goes stale: 5.0.0 shipped with six snippets still on 4.28.0.

const { version } = require(path.join(ROOT, 'package.json'));

for (const p of [path.join(ROOT, 'README.md'), ...DOCS]) {
  const md = read(p);
  if (!md) continue;
  const stale = new Set(
    all(md, /maverick-wave@([0-9]+\.[0-9]+\.[0-9]+)/g).filter(
      (v) => v !== version
    )
  );
  for (const v of stale) {
    errors.push(
      `stale CDN pin in ${path.relative(ROOT, p)}: maverick-wave@${v} - package.json is ${version}`
    );
  }
}

// --- 6: scroll timelines and the animation shorthand ------------------------
// A consumer bundler (esbuild among them) folds the longhands plus
// animation-timeline into one `animation: ... view()`, which no browser
// accepts - the declaration is dropped and the element never animates. It only
// shows up in the consuming project, never in our own build, so the source is
// what has to be clean: no shorthand in a file that uses a timeline.
// 5.0.0 and 5.2.0 both shipped empty progress bars this way.

for (const f of filesWithExt(path.join(ROOT, 'src', 'scss'), '.scss')) {
  const scss = read(f);
  if (!scss || !scss.includes('animation-timeline')) continue;
  for (const m of scss.match(/^\s*animation:.*/gm) || []) {
    errors.push(
      `${path.relative(ROOT, f)}: \`${m.trim()}\` - a file with a scroll timeline must use animation-* longhands, a bundler folds the shorthand and kills the timeline`
    );
  }
}

// Informational: framework classes the showcase never demonstrates
const undocumented = [...classesInCss].filter(
  (c) => !classesInMarkup.has(c) && !classesInJs.has(c)
);
if (undocumented.length) {
  warnings.push(
    `${undocumented.length} classes exist in the CSS but are not shown in the showcase`
  );
}

// --- report ----------------------------------------------------------------

const label = (n, s) => `${n} ${s}${n === 1 ? '' : 's'}`;

for (const w of warnings) console.log(`  warn   ${w}`);
for (const e of errors) console.error(`  ERROR  ${e}`);

console.log(
  `\nverify: ${tokensDefined.size} tokens, ${classesInCss.size} classes checked - ` +
    (errors.length ? `${label(errors.length, 'error')}` : 'clean')
);

process.exit(errors.length ? 1 : 0);
